Add README and nitial resource sharing plan
lab-carpentry/blueprint-resourcesharing pull request #1
Opened 2016-12-09 20:30 UTC by dhimmel

This resource sharing plan is based on one @cgreene and I wrote for a grant that @cgreene is submitting to the NIH.

The main goal is to ensure that project outputs are openly licensed, in spite of University ownership. 

Who [owns academic data/content is complicated](http://osc.universityofcalifornia.edu/2016/09/who-owns-your-data/), so these resource sharing plans should ensure open licensing regardless of owner.

Another goal is to prevent license incompatibilities down the road. Hence, the creators and investigators are provided the ability to release content as CC0.

Comments please!

2016-12-09 20:33 UTC, dhimmel commented
@jakevdp, I saw your [tweet on git for prose](https://twitter.com/jakevdp/status/796817091684769792).

Does the formatting of prose in this PR look good to you? Any suggestions to make maintaining prose easier?

2016-12-09 21:34 UTC, ethanwhite reviewed
I think this looks awesome. My one major suggestion is to think about where exactly this will end up for most funders and whether that means it might be worthwhile trying to shorten it. For NSF This would to in the Data Management plan. In my experience those aren't too tight on space so probably not a big deal, but if this needed to go in the proposal body (which it might have to in some cases; I've needed to do it that way in the past) it would be way too long. One option would be to add 2nd, 2-3 sentence version, designed to cover the 2nd use case.

2016-12-09 21:34 UTC, ethanwhite commented on README.md
> +Since Universities are generally the recipient of the grant and approve its content, a resource sharing plan can legally obligate a University allow the researchers to openly license their research.
"a University TO allow" or "that a University allow" ?

2016-12-09 22:13 UTC, jakevdp commented
> Does the formatting of prose in this PR look good to you?

Looks pretty good!

2016-12-09 22:22 UTC, cgreene commented
To go along with @ethanwhite's comment, you may want to specify that this is for NIH grants (where it does not count towards page limits). Maybe prefix `resource-sharing-plan.md` with nih so you have `nih-resource-sharing-plan.md`. Then as people work this into other grants, they may be willing to commit back ones that fit other funder requirements.

2016-12-09 23:41 UTC, strasser commented
I like it! There isn't as much detail as I would like to see in a data sharing plan from grantees, so you might also add that this might not be sufficient for all funders. Perhaps point to DCC or DMPTool as resource. Might ask Stephanie Simms from CDL/DMPtool to look? Can connect if you'd like

2016-12-10 00:07 UTC, cgreene requested changes
A few changes that I noticed.

2016-12-10 00:07 UTC, cgreene commented on README.md
> +Resource sharing plans can impose legally-binding obligations for University's to openly license research.
University's -> universities

2016-12-10 00:07 UTC, cgreene commented on README.md
> +Finally, a plan that commits to openness can make your proposal more attractive to funders.
During our recent labcarpentry discussion, we decided that our resources would be opinionated. I think you can change `can` to `should` here if you want to. This isn't a mandatory change.

2016-12-10 00:07 UTC, cgreene commented on README.md
> +For example, if you receive comments on your grant related to these resource sharing plans, we'd love to know.
How should somebody provide feedback?

2016-12-10 00:56 UTC, cgreene commented on README.md
>  Having a straightforward licensing arrangement can avoid delays down the road when seeking licensing approval from your University.
Unless it's a specific university, these should be lowercase.

2016-12-10 00:56 UTC, dhimmel commented
> you may want to specify that this is for NIH grants (where it does not count towards page limits).

@cgreene, done

> My one major suggestion is to think about where exactly this will end up for most funders and whether that means it might be worthwhile trying to shorten it.

@ethanwhite I changed the repository to be a collection of many examples. This initial example is for the NIH, where the resource sharing plan doesn't count as part of the grant size limit. Hopefully, we can get contributions with plans for alternative funders.

> There isn't as much detail as I would like to see in a data sharing plan from grantees, so you might also add that this might not be sufficient for all funders.

@strasser, I added the following to the prologue of the example:

> This plan largely focuses on ensuring the open licensing of project outputs. Carly Strasser — a Program Officer for the [Data-Driven Discovery Initiative](https://www.moore.org/initiative-strategy-detail?initiativeId=data-driven-discovery) at the Gordon & Betty Moore Foundation — [suggests](https://github.com/lab-carpentry/blueprint-resourcesharing/pull/1#issuecomment-266153553) adding more details regarding your specific data outputs and corresponding sharing plans. For inspiration, see the [Digital Curation Centre guide](http://www.dcc.ac.uk/resources/how-guides/develop-data-plan "How to Develop a Data Management and Sharing Plan") or [public Data Management Plans](https://dmptool.org/public_dmps "DMPTool").

2016-12-10 00:56 UTC, cgreene approved these changes
One minor comment around capitalization. After addressing this, it will LGTM 👍 Probably good to give others some time to give additional input before merging.

2016-12-12 14:55 UTC, cgreene commented
@dhimmel : when you merge, can you either file a PR or an issue against the website repo? We'll want to edit https://github.com/lab-carpentry/lab-carpentry.github.io/blob/master/pages/blueprints.md to link to this resource.

2016-12-13 16:28 UTC, merged